- name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name nginx-cluster
     # Step to register task definition
      - name: Register Task Definition
        run: |
          aws ecs register-task-definition \
            --family nginx-task \
            --container-definitions '[{"name":"view","image":"222634385188.dkr.ecr.us-west-1.amazonaws.com/view","portMappings":[{"containerPort":80}],"memoryReservation":128}]'
     # Step to create ECS service
      - name: Create ECS Service
        run: |
          aws ecs create-service \
            --cluster nginx-cluster \
            --service-name nginx-service \
            --task-definition nginx-task \
            --desired-count 1 \
            --launch-type EC2 \
            --region ${{ env.AWS_REGION }}
